### ISSUE TITLE
Segmentation fault vpu_decoder->decoder_context

### ISSUE THREAD

**Issue by MathiasDierickx** [Freescale/gstreamer-imx#149]
Hello,

I get a segmentation fault when a new frame is pushed to the decoder and I stop the gstreamer pipeline from another thread at the same time.

Looking in the code of decoder.c, I see following situation:

```
static void gst_imx_vpu_decoder_close_and_clear_decoder_context(GstImxVpuDecoder *vpu_decoder)  {
...
GST_IMX_VPU_DECODER_CONTEXT_UNLOCK(vpu_decoder->decoder_context);

gst_object_unref(vpu_decoder->decoder_context);
vpu_decoder->decoder_context = NULL;
```
while gst_imx_vpu_decoder_change_state is waiting for the lock. 

By the time the function gst_imx_vpu_decoder_change_state gets the lock, vpu_decoder->decoder_context = NULL is done immediately in another thread. Then the function call gst_imx_vpu_decoder_context_set_no_wait in gst_imx_vpu_decoder_change_state is causing a segmentation fault because of a nullptr. 

Backtrace when the segfault happens (notice decoder_context=0x0):

```
Thread 10 (LWP 18687):
#0  gst_imx_vpu_decoder_context_set_no_wait (decoder_context=0x0, no_wait=1) at ../src/vpu/decoder_context.c:128
#1  0x58d64960 in gst_imx_vpu_decoder_change_state (element=0x4c15ed18, transition=GST_STATE_CHANGE_PAUSED_TO_READY) at ../src/vpu/decoder.c:1088
#2  0x75761670 in gst_element_change_state (element=element@entry=0x4c15ed18, transition=transition@entry=GST_STATE_CHANGE_PAUSED_TO_READY) at gstelement.c:2602
#3  0x75761c14 in gst_element_set_state_func (element=0x4c15ed18, state=<optimized out>) at gstelement.c:2558
#4  0x7573ff10 in gst_bin_element_set_state (next=<optimized out>, current=<optimized out>, start_time=113147013248, base_time=6348117399002152963, element=0x4c15ed18, bin=<optimized out>) at gstbin.c:2328
#5  gst_bin_change_state_func (element=0x58190b18, transition=0) at gstbin.c:2665
#6  0x75761670 in gst_element_change_state (element=element@entry=0x58190b18, transition=transition@entry=GST_STATE_CHANGE_PAUSED_TO_READY) at gstelement.c:2602
#7  0x75761c14 in gst_element_set_state_func (element=0x58190b18, state=<optimized out>) at gstelement.c:2558
#8  0x7573ff10 in gst_bin_element_set_state (next=<optimized out>, current=<optimized out>, start_time=112945320344, base_time=5481270334403379203, element=0x58190b18, bin=<optimized out>) at gstbin.c:2328
#9  gst_bin_change_state_func (element=0x4c116248, transition=0) at gstbin.c:2665
#10 0x75785c74 in gst_pipeline_change_state (element=0x4c116248, transition=GST_STATE_CHANGE_PAUSED_TO_READY) at gstpipeline.c:469
#11 0x75761670 in gst_element_change_state (element=0x4c116248, transition=transition@entry=1276207700) at gstelement.c:2602
#12 0x75761f88 in gst_element_continue_state (element=<optimized out>, ret=<optimized out>) at gstelement.c:2312
#13 0x75761724 in gst_element_change_state (element=element@entry=0x4c116248, transition=transition@entry=GST_STATE_CHANGE_PLAYING_TO_PAUSED) at gstelement.c:2646
#14 0x75761c14 in gst_element_set_state_func (element=0x4c116248, state=<optimized out>) at gstelement.c:2558


Thread 126 (LWP 30682):
#0  0x738fcb1c in ioctl () from /lib/libc.so.6
#1  0x76d98d14 in _IOGetPhyMem (which=<optimized out>, buff=0x575b2758) at vpu_io.c:530
#2  0x76da3828 in vpu_DecOpen (pHandle=<optimized out>, pop=pop@entry=0x476d3580) at vpu_lib.c:2659
#3  0x75be8b94 in imx_vpu_dec_open (decoder=decoder@entry=0x4c15ef10, open_params=0x476d3644, open_params@entry=0x0, bitstream_buffer=0x3417200, new_initial_info_callback=<optimized out>,
#4  0x58d66f34 in gst_imx_vpu_decoder_set_format (decoder=0x4c15ed18, state=0x57167ac0) at ../src/vpu/decoder.c:433
#5  0x76ec8fd0 in gst_video_decoder_setcaps (caps=0x341c4c8, decoder=0x4c15ed18) at gstvideodecoder.c:788
#6  gst_video_decoder_chain (pad=<optimized out>, parent=0x4c15ed18, buf=0x571675d8) at gstvideodecoder.c:2130
#7  0x7577914c in gst_pad_chain_data_unchecked (pad=pad@entry=0x4c118d08, type=type@entry=4112, data=data@entry=0x571675d8) at gstpad.c:3830
#8  0x7577ad28 in gst_pad_push_data (pad=0x4c118bc0, type=type@entry=4112, data=data@entry=0x571675d8) at gstpad.c:4063
#9  0x75781e04 in gst_pad_push (pad=<optimized out>, buffer=buffer@entry=0x571675d8) at gstpad.c:4174
#10 0x737ee64c in gst_base_parse_push_frame (parse=parse@entry=0x58153838, frame=frame@entry=0x697e7b38) at gstbaseparse.c:2304
#11 0x737f1d9c in gst_base_parse_handle_and_push_frame (frame=0x697e7b38, parse=0x58153838) at gstbaseparse.c:2136
#12 gst_base_parse_finish_frame (parse=parse@entry=0x58153838, frame=frame@entry=0x697e7b38, size=size@entry=38412) at gstbaseparse.c:2461
#13 0x58c8e2f0 in gst_h264_parse_handle_frame (parse=0x58153838, frame=0x697e7b38, skipsize=0x57188b48) at gsth264parse.c:1051
#14 0x737ea3fc in gst_base_parse_handle_buffer (parse=parse@entry=0x58153838, buffer=<optimized out>, skip=0x476d3b44, skip@entry=0x476d3b3c, flushed=0x0, flushed@entry=0x476d3b40) at gstbaseparse.c:1963
#15 0x737ef22c in gst_base_parse_chain (pad=<optimized out>, parent=0x58153838, buffer=<optimized out>) at gstbaseparse.c:2899
#16 0x7577914c in gst_pad_chain_data_unchecked (pad=pad@entry=0x4c118a78, type=type@entry=4112, data=data@entry=0x4c17fa20) at gstpad.c:3830
#17 0x7577ad28 in gst_pad_push_data (pad=0x4c118930, type=type@entry=4112, data=data@entry=0x4c17fa20) at gstpad.c:4063
#18 0x75781e04 in gst_pad_push (pad=<optimized out>, buffer=buffer@entry=0x4c17fa20) at gstpad.c:4174
#19 0x57f22408 in gst_queue_push_one (queue=0x581ab320) at gstqueue.c:1169
#20 gst_queue_loop (pad=<optimized out>) at gstqueue.c:1298
#21 0x757af5a0 in gst_task_func (task=0x571aa2c8) at gsttask.c:316
```

**Comment by ahresse** [comment]
Hello, do you have any update on this issue?
