### ISSUE TITLE
imxvpudec opens two decoder instance for h264 but closes only one

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#227]
With every gst_video_decoder_setcaps a call for gst_imx_vpu_decoder_set_format  a new vpu_DecOpen is called but not freed. 

It seems to happen if a pipeline gets new sink added to a tee. This gdb output shows what happens:
```
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-angstrom-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./drgstreamer...done.
(gdb) b vpu_DecOpen
Function "vpu_DecOpen" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (vpu_DecOpen) pending.
(gdb) r -s0
Starting program: /home/root/drgstreamer -s0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x764a0a88 in ?? () from /usr/lib/libcrypto.so.1.0.2
(gdb) c
Continuing.
[New Thread 0x7603a3f0 (LWP 8490)]
[New Thread 0x756ff3f0 (LWP 8492)]
[New Thread 0x74cff3f0 (LWP 8493)]
[New Thread 0x742ff3f0 (LWP 8500)]
[New Thread 0x738ff3f0 (LWP 8501)]
[New Thread 0x72eff3f0 (LWP 8503)]
[New Thread 0x724ff3f0 (LWP 8505)]
[New Thread 0x71aff3f0 (LWP 8506)]
[New Thread 0x712fe3f0 (LWP 8507)]
[New Thread 0x70afd3f0 (LWP 8513)]
[New Thread 0x6757a3f0 (LWP 8520)]
[New Thread 0x66d793f0 (LWP 8521)]
[Switching to Thread 0x6757a3f0 (LWP 8520)]

Thread 12 "h264_src1:src" hit Breakpoint 1, vpu_DecOpen (pHandle=0x72f12130, pop=pop@entry=0x67579268) at /usr/src/debug/imx-vpu/1_5.4.38-r0/imx-vpu-5.4.38/vpu_lib.c:2629
2629            ENTER_FUNC();
(gdb) bt
#0  0x73aaa238 in vpu_DecOpen (pHandle=0x72f12130, pop=pop@entry=0x67579268) at /usr/src/debug/imx-vpu/1_5.4.38-r0/imx-vpu-5.4.38/vpu_lib.c:2629
#1  0x74e0c75e in imx_vpu_dec_open (decoder=decoder@entry=0x1d84a0, open_params=open_params@entry=0x67579324, bitstream_buffer=0x1c8c00, new_initial_info_callback=0x75814989 <gst_imx_vpu_decoder_initial_info_callback>, callback_user_data=callback_user_data@entry=0x1d82a8) at /usr/src/debug/libimxvpuapi/0.10.3+AUTOINC+4afb52f97e-r0/git/imxvpuapi/imxvpuapi_vpulib.c:1083
#2  0x758167ca in gst_imx_vpu_decoder_set_format (decoder=0x1d82a8 [GstImxVpuDecoder], state=0x72f11830) at /usr/src/debug/gstreamer1.0-plugins-imx/0.13.0+gitAUTOINC+963aea60b1-r0/git/src/vpu/decoder.c:449
#3  0x744a7966 in gst_video_decoder_setcaps (caps=0x72f0f0a0, decoder=0x1d82a8 [GstImxVpuDecoder]) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/video/gstvideodecoder.c:697
#4  0x744a7966 in gst_video_decoder_sink_event_default (decoder=0x1d82a8 [GstImxVpuDecoder], event=0x71b05520) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/video/gstvideodecoder.c:1117
#5  0x76f0811a in gst_pad_send_event_unchecked (pad=pad@entry=0x1c4a68 [GstPad], event=event@entry=0x71b05520, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5675
#6  0x76f08524 in gst_pad_push_event_unchecked (pad=pad@entry=0x1c4908 [GstPad], event=0x71b05520, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5331
#7  0x76f088c0 in push_sticky (pad=0x1c4908 [GstPad], ev=0x67579590, user_data=0x675795d4) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3857
#8  0x76f06c94 in events_foreach (pad=pad@entry=0x1c4908 [GstPad], func=0x76f08839 <push_sticky>, user_data=user_data@entry=0x675795d4) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:611
#9  0x76f107da in check_sticky (event=0x71b05520, pad=0x1c4908 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3916
#10 0x76f107da in gst_pad_push_event (pad=pad@entry=0x1c4908 [GstPad], event=0x71b05520) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5462
#11 0x74e58150 in gst_pad_set_caps (caps=0x72f0f0a0, pad=0x1c4908 [GstPad]) at /usr/include/gstreamer-1.0/gst/gstcompat.h:59
#12 0x74e58150 in gst_h264_parse_update_src_caps (h264parse=h264parse@entry=0x1d14d0 [GstH264Parse], caps=<optimized out>, caps@entry=0x1a6e78)
    at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:1962
#13 0x74e59774 in gst_h264_parse_set_caps (parse=0x1d14d0 [GstH264Parse], caps=<optimized out>) at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:2697
#14 0x74e8a3ce in gst_base_parse_sink_event_default (parse=0x1d14d0 [GstH264Parse], event=0x71b054d8) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbaseparse.c:1153
#15 0x74e56b58 in gst_h264_parse_event (parse=0x1d14d0 [GstH264Parse], event=0x71b054d8) at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:2867
#16 0x76f0811a in gst_pad_send_event_unchecked (pad=pad@entry=0x1c47a8 [GstPad], event=event@entry=0x71b054d8, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5675
#17 0x76f08524 in gst_pad_push_event_unchecked (pad=pad@entry=0x1c4648 [GstPad], event=0x71b054d8, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5331
#18 0x76f088c0 in push_sticky (pad=0x1c4648 [GstPad], ev=0x67579a40, user_data=0x67579a84) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3857
#19 0x76f06c94 in events_foreach (pad=pad@entry=0x1c4648 [GstPad], func=0x76f08839 <push_sticky>, user_data=user_data@entry=0x67579a84) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:611
#20 0x76f107da in check_sticky (event=0x71b054d8, pad=0x1c4648 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3916
#21 0x76f107da in gst_pad_push_event (pad=pad@entry=0x1c4648 [GstPad], event=0x71b054d8) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5462
#22 0x74e9c1e2 in gst_base_src_set_caps (src=src@entry=0x1ce198 [GstAppSrc], caps=caps@entry=0x1a6e78) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbasesrc.c:912
#23 0x7582448e in gst_app_src_do_negotiate (basesrc=basesrc@entry=0x1ce198 [GstAppSrc]) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/app/gstappsrc.c:1070
#24 0x7582462e in gst_app_src_create (bsrc=0x1ce198 [GstAppSrc], offset=0, size=4096, buf=0x67579c34) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/app/gstappsrc.c:1171
#25 0x74e9916a in gst_base_src_get_range (src=src@entry=0x1ce198 [GstAppSrc], offset=0, length=<optimized out>, length@entry=4096, buf=buf@entry=0x67579cf4) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbasesrc.c:2453
#26 0x74e9a856 in gst_base_src_loop (pad=0x1c4648 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbasesrc.c:2729
#27 0x76f31c5c in gst_task_func (task=0x1c22c8 [GstTask]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gsttask.c:335
#28 0x76e030cc in g_thread_pool_thread_proxy (data=<optimized out>) at /usr/src/debug/glib-2.0/1_2.54.3-r0/glib-2.54.3/glib/gthreadpool.c:307
#29 0x76e029ae in g_thread_proxy (data=0xf2af0) at /usr/src/debug/glib-2.0/1_2.54.3-r0/glib-2.54.3/glib/gthread.c:784
#30 0x76d48524 in start_thread (arg=0xad33d291) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
#31 0x76bb747c in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
(gdb) c
Continuing.
OPEN INSTANCE 0x67af6008
[INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0

Thread 12 "h264_src1:src" hit Breakpoint 1, vpu_DecOpen (pHandle=0x72f123f8, pop=pop@entry=0x67579488) at /usr/src/debug/imx-vpu/1_5.4.38-r0/imx-vpu-5.4.38/vpu_lib.c:2629
2629            ENTER_FUNC();
(gdb) bt
#0  0x73aaa238 in vpu_DecOpen (pHandle=0x72f123f8, pop=pop@entry=0x67579488) at /usr/src/debug/imx-vpu/1_5.4.38-r0/imx-vpu-5.4.38/vpu_lib.c:2629
#1  0x74e0c75e in imx_vpu_dec_open (decoder=decoder@entry=0x1d84a0, open_params=open_params@entry=0x67579544, bitstream_buffer=0x1c8c00, new_initial_info_callback=0x75814989 <gst_imx_vpu_decoder_initial_info_callback>, callback_user_data=callback_user_data@entry=0x1d82a8) at /usr/src/debug/libimxvpuapi/0.10.3+AUTOINC+4afb52f97e-r0/git/imxvpuapi/imxvpuapi_vpulib.c:1083
#2  0x758167ca in gst_imx_vpu_decoder_set_format (decoder=0x1d82a8 [GstImxVpuDecoder], state=0x72f11900) at /usr/src/debug/gstreamer1.0-plugins-imx/0.13.0+gitAUTOINC+963aea60b1-r0/git/src/vpu/decoder.c:449
#3  0x744a7966 in gst_video_decoder_setcaps (caps=0x72f0f568, decoder=0x1d82a8 [GstImxVpuDecoder]) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/video/gstvideodecoder.c:697
#4  0x744a7966 in gst_video_decoder_sink_event_default (decoder=0x1d82a8 [GstImxVpuDecoder], event=0x71b055f8) at /usr/src/debug/gstreamer1.0-plugins-base/1.12.4-r0/gst-plugins-base-1.12.4/gst-libs/gst/video/gstvideodecoder.c:1117
#5  0x76f0811a in gst_pad_send_event_unchecked (pad=pad@entry=0x1c4a68 [GstPad], event=event@entry=0x71b055f8, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM)
    at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5675
#6  0x76f08524 in gst_pad_push_event_unchecked (pad=pad@entry=0x1c4908 [GstPad], event=0x71b055f8, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5331
#7  0x76f088c0 in push_sticky (pad=0x1c4908 [GstPad], ev=0x675797b0, user_data=0x675797f4) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3857
#8  0x76f06c94 in events_foreach (pad=pad@entry=0x1c4908 [GstPad], func=0x76f08839 <push_sticky>, user_data=user_data@entry=0x675797f4) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:611
#9  0x76f107da in check_sticky (event=0x71b055f8, pad=0x1c4908 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:3916
#10 0x76f107da in gst_pad_push_event (pad=pad@entry=0x1c4908 [GstPad], event=0x71b055f8) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:5462
#11 0x74e58150 in gst_pad_set_caps (caps=0x72f0f568, pad=0x1c4908 [GstPad]) at /usr/include/gstreamer-1.0/gst/gstcompat.h:59
#12 0x74e58150 in gst_h264_parse_update_src_caps (h264parse=h264parse@entry=0x1d14d0 [GstH264Parse], caps=<optimized out>, caps@entry=0x0) at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:1962
#13 0x74e59a0e in gst_h264_parse_parse_frame (parse=parse@entry=0x1d14d0 [GstH264Parse], frame=frame@entry=0x74305e08) at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:2119
#14 0x74e5a4aa in gst_h264_parse_handle_frame (parse=0x1d14d0 [GstH264Parse], frame=0x74305e08, skipsize=0x67579b8c) at /usr/src/debug/gstreamer1.0-plugins-bad/1.12.4-r0/gst-plugins-bad-1.12.4/gst/videoparsers/gsth264parse.c:1273
#15 0x74e85262 in gst_base_parse_handle_buffer (parse=parse@entry=0x1d14d0 [GstH264Parse], buffer=0x73965988, skip=skip@entry=0x67579b8c, flushed=flushed@entry=0x67579b90)
    at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbaseparse.c:2153
#16 0x74e89dba in gst_base_parse_chain (pad=<optimized out>, parent=0x1d14d0 [GstH264Parse], buffer=<optimized out>) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbaseparse.c:3235
#17 0x76f09170 in gst_pad_chain_data_unchecked (data=0x73965988, type=4112, pad=0x1c47a8 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:4257
#18 0x76f09170 in gst_pad_push_data (pad=pad@entry=0x1c4648 [GstPad], type=type@entry=4112, data=data@entry=0x73965988) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:4513
#19 0x76f0faee in gst_pad_push (pad=pad@entry=0x1c4648 [GstPad], buffer=0x73965988) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gstpad.c:4632
#20 0x74e9a9f4 in gst_base_src_loop (pad=0x1c4648 [GstPad]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/libs/gst/base/gstbasesrc.c:2843
#21 0x76f31c5c in gst_task_func (task=0x1c22c8 [GstTask]) at /usr/src/debug/gstreamer1.0/1.12.4-r0/gstreamer-1.12.4/gst/gsttask.c:335
#22 0x76e030cc in g_thread_pool_thread_proxy (data=<optimized out>) at /usr/src/debug/glib-2.0/1_2.54.3-r0/glib-2.54.3/glib/gthreadpool.c:307
#23 0x76e029ae in g_thread_proxy (data=0xf2af0) at /usr/src/debug/glib-2.0/1_2.54.3-r0/glib-2.54.3/glib/gthread.c:784
#24 0x76d48524 in start_thread (arg=0xad33d291) at /usr/src/debug/glibc/2.27-r0/git/nptl/pthread_create.c:463
#25 0x76bb747c in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
(gdb)
```
Is that a design problem or can we I work around it?

Thanks a lot in advance - best regards Sascha

**Comment by dv1** [comment]
Hi. Sorry for the silence. I am hard at work on imxvpuapi imx8 support. I got the encoder to work, and am now adapting gstreamer-imx for it. This unfortunately takes up all of my time, so I cannot help at the moment. Since gstreamer-imx will be pretty much rewritten, I recommend waiting a few more days until I can create a v2 branch with the new stuff in it.

**Comment by angolini** [comment]
Can you, please, test with the latest release and update here with the status, @dierberg ?
