### ISSUE TITLE
Error when cross compile

### ISSUE THREAD

**Issue by Malek44** [Freescale/gstreamer-imx#71]
Hi,

I am trying to compile gstreamer-imx for ixm6q running linux 3.10.7
I have a cross compiler installed on my desktop computer.
I set properly the needed vars as requested by the readme:

PATH=/opt/poky/1.6.1/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/poky/1.6.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi:$PATH
SDKTARGETSYSROOT=/opt/poky/1.6.1/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi
CC="arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=$SDKTARGETSYSROOT"
LD="arm-poky-linux-gnueabi-ld  --sysroot=$SDKTARGETSYSROOT"
LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
CFLAGS=" -O2 -pipe -feliminate-unused-debug-types"
PKG_CONFIG_SYSROOT_DIR=$SDKTARGETSYSROOT
PKG_CONFIG_PATH=$SDKTARGETSYSROOT/usr/lib/pkgconfig

Then, I configured with:
./waf configure --prefix=/opt/imx_gst --kernel-headers=/opt/poky/1.6.1/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/src/kernel/include/

But, I get:
Traceback (most recent call last):
  File "./waf", line 162, in <module>
    from waflib import Scripting
  File "/home/xv/gstreamer-imx/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/xv/gstreamer-imx/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Utils.py", line 6, in <module>
    import subprocess
ImportError: No module named subprocess

Note that I have both Pyhon2.7 and 3.0 installed.

**Comment by dv1** [comment]
I honestly don't know what to do there. This hints at a Python installation problem. subprocess is a core part of Python. Strange that it isn't available. waf does not do anything funky with the modules. Check that your Python installation is correct, and that you can import subprocess in a Python shell.

**Comment by dv1** [comment]
Closing due to inactivity.
